module.exports=[
    {
        img:"https://joyfoodsunshine.com/wp-content/uploads/2018/02/best-chocolate-chip-cookies-recipe-3.jpg",
        name: "Chocolate Chip Cookies",
        ingredients:[
            "1 cup Chocolate chips",
            "1/2 cup Brown Sugar",
            "1 cup of Flour"
        ],
        recipe: "Preheat oven to 375 degrees F.\n Line a baking pan with parchment paper and set aside.\n In a separate bowl mix flour, baking soda, salt, baking powder.\n Set aside.\n Cream together butter and sugars until combined.\n Beat in eggs and vanilla until fluffy.\n Mix in the dry ingredients until combined.\n Add 12 oz package of chocolate chips and mix well.\n Roll 2-3 TBS (depending on how large you like your cookies) of dough at a time into balls and place them evenly spaced on your prepared cookie sheets. \n (alternately, use a small cookie scoop to make your cookies).\n Bake in preheated oven for approximately 8-10 minutes.\n Take them out when they are just BARELY starting to turn brown.\n Let them sit on the baking pan for 2 minutes before removing to cooling rack.\n",
        creator:"admin",
        createdDate: 12/27/2022,
},
{
    img:"https://www.cookingclassy.com/wp-content/uploads/2018/12/spinach-artichoke-dip-13.jpg",
    name:"Spinach Artichoke Dip",
    ingredients:["8 oz. cream cheese, well softened",
    "1/4 cup sour cream",
    "1/4 cup mayonnaise",
    "1 garlic clove, minced",
    "2/3 cup finely shredded parmesan cheese",
    "1/2 cup finely shredded mozzarella cheese",
    "Pepper, to taste",
    "1 (14 oz) can quartered artichoke hearts, can liquid drained, squeeze artichokes to drain excess liquid, chopped",
    "6 oz. frozen spinach, thawed, squeezed to drain excess liquid",
    ],
    recipe:["Preheat oven to 350 degrees.", 
    "Spray a small (1 quart) baking dish with non-stick cooking spray.",
    "In a mixing bowl stir together cream cheese, sour cream, mayonnaise, garlic, parmesan, mozzarella and pepper.",
    "Stir in artichokes and spinach.",
    "Spread mixture evenly into prepared baking dish.",
    "Bake in preheated oven until heated through and melty, about 20 minutes.",
    "Serve warm with tortilla chips, crackers or toasted baguette slices",
    ],
    creator:"https://www.cookingclassy.com/spinach-artichoke-dip/",
    createdDate:12/28/2022,
},
{
    img:"https://www.simplyrecipes.com/thmb/XqymJXoB2YZw2vHFgqpajv6QAr0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Simply-Recipes-Best-Classic-Lasagna-Lead-1-b67f9c8bb82448d7ac34807d0d62244e.jpg",
    name:"The Best Homemade Lasagna",
    ingredients:["2 teaspoons extra virgin olive oil",
        "1 pound ground beef chuck",
        "1/2 medium onion, diced (about 3/4 cup)",
        "1/2 large bell pepper (green, red, or yellow), diced (about 3/4 cup)",
        "2 cloves garlic, minced",
        "1 (28-ounce)can good-quality tomato sauce",
        "3 ounces tomato paste (half a 6-ounce can)",
        "1 (14 ounce) can crushed tomatoes",
        "2 tablespoons chopped fresh oregano, or 2 teaspoons dried oregano",
        "1/4 cup chopped fresh parsley (preferably flat leaf), packed",
        "1 tablespoon Italian seasoning",
        "1 pinch garlic powder and/or garlic salt",
        "1 tablespoon red or white wine vinegar",
        "1 tablespoon to 1/4 cup sugar (to taste, optional)",
        "Salt",        
        "1/2 pound dry lasagna noodles (requires 9 lasagna noodles - unbroken)",
        "15 ounces ricotta cheese",
        "1 1/2 pounds (24 ounces) mozzarella cheese, grated or sliced",
        "1/4 pound (4 ounces) freshly grated Parmesan cheese]",
],
    recipe:["Put a large pot of salted water (1 Tbsp salt for every 2 quarts of water) on the stovetop on high heat. It can take a while for a large pot of water to come to a boil (this will be your pasta water), so prepare the sauce in the next steps while the water is heating.",
    "In a large skillet heat 2 teaspoons of olive oil on medium high heat. Add the ground beef and cook until it is lightly browned on all sides.",
    "Add the diced bell pepper and onions to skillet (in the photo we are using yellow bell pepper and red onions).",
    "Cook for 4 to 5 minutes, until the onions are translucent and the peppers softened. Add the minced garlic and cook half a minute more.",
    "Return the browned ground beef to the pan. Stir to combine, reduce the heat to low and cook for another 5 minutes.",
    "Cook pasta",
    "In a 9x13-inch casserole or lasagna dish, ladle a cup of sauce and spread it over the bottom of the dish. Arrange one layer of lasagna noodles lengthwise (about 3 long noodles, edge may overlap, depending on your pan) over the sauce. Ladle a third of the remaining sauce over the noodles.",
    "Sprinkle a layer of a third of the grated mozzarella on top of lasagna sauce. Add half of the ricotta cheese, by placing cheese dollops every couple inches. Sprinkle half the grated parmesan cheese evenly over the top of ricotta cheese.",
    "Apply second layer of noodles, top it with half of the remaining sauce. Add half of the remaining Mozzarella, the remaining ricotta cheese, and another the remaining Parmesan.",
    "Finish with another layer of noodles. Spread the remaining sauce over the top layer of noodles and sprinkle with the remaining Mozzarella cheese.",
],
    creator:"https://www.simplyrecipes.com/recipes/lasagna/",
    createdDate:12/28/2022,
},
{
    img:"https://divascancook.com/wp-content/uploads/2009/12/southern-baked-macaroni-and-cheese-1.jpg.webp",
    name:"Southern Mac and Cheese",
    ingredients:["3 cups elbow macaroni, uncooked",
    "1 ½ cups milk",
    "1/2 cup heavy whipping cream",
    "1 cup Colby & Monterey Jack, shredded (cheese blend)",
    "6-8 oz Velveeta cheese, shredded",
    "1 cup sharp cheddar, shredded",
    "salt & pepper, to taste",
    "2 eggs",
    "1 cup smoked cheddar cheese, shredded (a must)",
    "paprika, optional"],
    recipe:["Preheat oven to 350 F.",
    "Cook macaroni until just al dente or a little under al dente. (Look on the back of the box to see how long you need to cook your pasta for it to reach al dente.) Be careful not to overcook.",
    "Drain pasta and set aside.",
    "In a large bowl, add milk, heavy cream & cheeses (except for the smoked cheddar).",
    "Stir to combine.",
    "Taste the milk mixture and add salt & pepper until it has a good taste.",
    "When you are content with the taste, add the eggs.",
    "Stir well until combined.",
    "Butter a 9 x 9-inch baking dish.",
    "Add macaroni to the baking dish.",
    "Pour cheese mixture over macaroni.",
    "Make sure the cheese is distributed well.",
    "Top with the smoked cheddar cheese. (I add a little more Colby jack as well.) Sprinkle with paprika and/or black pepper, if desired.",
    "Bake for 35-45 minutes. Do not overbake. It may be a bit jiggly when you take it out of the oven. It will firm up as it cool.",
    "Let cool for about 10-15 minutes or until fully set.",
    ],
    creator:"https://divascancook.com/southern-baked-macaroni-and-cheese-recipe/",
    createdDate:12/28/2022,
},
{
    img:"https://divascancook.com/wp-content/uploads/2021/01/IMG_9816-2048x1365.jpg.webp",
    name:"Sweet Honey Cornbread",
    ingredients:["1 ½ cups yellow cornmeal",
    "3/4 cup all-purpose flour",
    "1 tablespoon baking powder",
    "1/2 teaspoon salt",
    "1/4 teaspoon baking soda",
    "1/4 cup granulated sugar",
    "1/4 cup honey",
    "1 egg yolk, room temperature",
    "2 eggs, room temperature",
    "1/2 cup unsalted butter, melted, (1 stick)",
    "1 tablespoon canola oil",
    "1½ cups buttermilk, room temperature"],
    recipe:["Preheat oven to 450 F. Grease a 8x8 glass casserole dish and set aside.",
    "In a large bowl whisk together yellow cornmeal, flour, baking powder, salt, baking soda, and sugar. Set aside.",
    "In a large bowl, mix together remaining ingredients until well combined.",
    "Stir the wet ingredients into the dry ingredients just until all ingredients are combined. Do not over stir. It's fine if the batter is a bit lumpy.",
    "Spoon batter into prepared pan and smooth out into an even layer.",
    "Bake for 25-30 minutes, or until the center is set. (check on it at the 20 minute mark) Cover with foil paper during the last 5-10 minutes if it begins to get too brown.",
    "Remove from oven and prepare the honey butter.",
    "To make the honey butter, combine all the honey butter ingredients until smooth and creamy.",
    "Immediately spread honey butter over hot cornbread. (Use as much as you like)",
    "Slice cornbread into squares and serve with leftover honey butter if desired."],
    creator:"https://divascancook.com/sweet-cornbread-recipe-honey-moist/",
    createdDate:12/28/2022,
},
]
